language: java
sudo: true
jdk:
  - oraclejdk8
# not supported yet
#  - openjdk8
before_install:
  - "sh -e /etc/init.d/xvfb start"
  - "mvn --version"
addons:
  apt:
    packages:
    - r-cran-rjava
env:
  - DISPLAY=:99.0
  - CLASSPATH=.:/usr/lib/R/site-library/rJava/jri/
  - R_HOME=/usr/lib/R
branches:
  only:
    - master
cache:
  directories:
    - $HOME/.m2
