language: java
sudo: false
jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8
before_install:
  - "sh -e /etc/init.d/xvfb start"
  - "mvn --version"
env:
  - DISPLAY=:99.0
branches:
  only:
    - master
