language: java
sudo: true
services:
  - xvfb
jdk:
  - openjdk11
  - openjdk14
before_install:
  - "mvn --version"
  - "export CLASSPATH=.:/usr/lib/R/site-library/rJava/jri/"
  - "export R_HOME=/usr/lib/R"
matrix:
  allow_failures:
    - jdk: openjdk14
addons:
  apt:
    packages:
      - r-cran-rjava
      - libjhdf5-jni
env:
  - DISPLAY=:99.0
branches:
  only:
    - master
cache:
  directories:
    - $HOME/.m2
